name: CronJob - Liquidator Bot - Ethereum Mainnet
on:
  schedule:
    - cron: "50 * * * *" # ie. 4:50pm, 5:50pm ... etc.
env:
  CHAIN_ID: 1
  MIN_PROFIT_THRESHOLD_USD: 90
  SWAP_RECIPIENT: ''
  JSON_RPC_URL: ${{ secrets.ETHEREUM_MAINNET_JSON_RPC_URL }}
  COVALENT_API_KEY: ${{ secrets.COVALENT_API_KEY }}
  CUSTOM_RELAYER_PRIVATE_KEY: ${{ secrets.CUSTOM_RELAYER_PRIVATE_KEY }}
  CONTRACT_JSON_URL: 'https://raw.githubusercontent.com/GenerationSoftware/pt-v5-mainnet/ca2acf967a962355b921fd4893306b961e7bc62a/deployments/ethereum/contracts.json'
  ENV_TOKEN_ALLOW_LIST: ''
  NODE_OPTIONS: "--max_old_space_size=32768"
permissions: write-all
jobs:
  runCLI:
    name: Liquidator Bot
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: ["20.11.1"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Store current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
      
      - name: Store current time
        id: time
        run: echo "time=$(date +'%H-%M-%S_%Z')" >> "$GITHUB_ENV"

      - name: Check environment variables
        id: checkEnv
        run: |
          if [[ -z "$JSON_RPC_URL" || -z "$CUSTOM_RELAYER_PRIVATE_KEY" || -z "$CONTRACT_JSON_URL" ]]; then
            echo "can_run=false" >> "$GITHUB_OUTPUT"
          else
            echo "can_run=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run bot
        id: runBot
        if: steps.checkEnv.outputs.can_run == 'true'
        run: |
          npm install
          npx tsx index.ts

      - name: Push changes (if required)
        if: steps.checkEnv.outputs.can_run == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
